define({
  "root": {
    "attributes": {
      "title": "Title",
      "backupDatabase": "Backup Database",
      "restoreDatabase": "Restore Database",
      "domain": "Base Url"
    },
    "development": "Development",
    "backend_development": "Backend in Development Mode",
    "frontend_development": "Frontend in Development Mode",
    "cancel": "Cancel",
    "deleteModel": "Delete",
    "save": "Save",
    "publish": "Publish",
    "unpublish": "Unpublish",
    "navigation": "General",
    "date": "Date",
    "dateformat": "%d.%m.%y %H:%m:%S",
    "sunday": "Sunday",
    "monday": "Monday",
    "tuesday": "Tuesday",
    "wednesday": "Wednesday",
    "thursday": "Thursday",
    "friday": "Friday",
    "saturday": "Saturday",
    "january": "January",
    "february": "February",
    "march": "March",
    "april": "April",
    "may": "May",
    "june": "June",
    "july": "July",
    "august": "August",
    "september": "September",
    "october": "October",
    "november": "November",
    "december": "December"
  },
  "de": true
});
