define({
  "preview": "Voransicht",
  "previewview": "Magazine",
  "description": "Erstelle und editiere Magazine",
  "addFiles": "Files hinzufuegen...",
  "headline": "Magazines",
  "navigation": "Magazine",
  "attributes": {
    "layouts": "Layouts",
    "theme": "Theme",
    "print": "Aktiviere Druck PDF",
    "cover": "Cover Image",
    "back": "Back Image",
    "publish": "Publish",
    "unpublish": "Unpublish",
    "downloadPdf": "Download Druck Pdf",
    "details": "Magazine Details",
    "title": "Title",
    "author": "Author",
    "article": "Artikel",
    "product_id": "Produkt ID",
    "info": "Info",
    "impressum": "Impressum",
    "editorial": "Editorial",
    "magazine": "Magazine",
    "papersize": "Papierformat auswählen (Druck)",
    "orientation": "Paperausrichtung auswählen (Druck)",
    "layout": "Layout"
  },
  "fileDescription": "Use 'cover' and 'back' templates keys",
  "newModel": "hat eines Neues Magazine erstellt",
  "updateModel": "hat ein Magazine aktualisiert",
  "emptyMessage": "Das Magazine existiert nicht mehr",
  "deleteModel": "hat ein Magazine gelöscht"
});
// define({
// 	"pageHeadline": "Seiten",
// 	"cover": "Titelseite",
// 	"back": "Rückseite",
// 	"downloadHpub": "Download hpub",
// 	"index": "Inhaltsverzeichnis",
// 	"editorial": "Editorial",
//  "addPage": "Seite hinzufügen",
//  "navigation": "Magazine",
//  "layouts": "Vorlagen",
//  "theme": "Design",
//  "print": "Druck Pdf's aktivieren",
//  "details": "Magazin Details",
//  "title": "Titel",
//  "author": "Autor",
//  "publish": "Publish",
//  "unpublish": "Unpublish",
//  "downloadPdf": "Druck PDF",
//  "impressum": "Impressum",
//  "editorial": "Editorial",
//  "product_id": "Produkt ID",
//     "info": "Info",
//     "fileDescription": "Use 'cover' and 'back' templates keys",
//  "papersize": "Papierformat auswählen (Druck)",
//  "orientation": "Paperausrichtung auswählen (Druck)",
//  "newMagazine": "hat eines Neues Magazine erstellt",
//     "updateMagazine": "hat ein Magazine aktualisiert",
//     "emptyMessage": "Das Magazine existiert nicht mehr",
//     "deleteMagazine": "hat ein Magazine gelöscht"
// });
