define({
  "previewview": "Files",
  "description": "add and edit files",
  "addFiles": "Dateien hinzufügen...",
  "addFile": "Datei hinzufügen...",
  "headline": "Files",
  "navigation": "Files",
  "emptyMessage": "The file does not exist anymore",
  "newModel": "uploaded new file",
  "deleteModel": "deleted file",
  "updateModel": "updated file",
  "attributes": {
    "details": "File details",
    "thumbnail": "Vorschau Thumbnail größe",
    "smallPic": "Kleine Bilder größe",
    "bigPic": "Größe Bilder größe",
    "quality": "Bilde Qualität",
    "info": "Info",
    "name": "Name",
    "title": "Name",
    "desc": "Beschreibung",
    "alt": "Alt",
    "key": "Schlüssel",
    "type": "Filetyp",
  },
});
