define({
  "previewview": "Files",
  "description": "add and edit files",
  "addFiles": "Add files...",
  "headline": "Files",
  "navigation": "Files",
  "emptyMessage": "The file does not exist anymore",
  "newModel": "uploaded new file",
  "deleteModel": "deleted file",
  "updateModel": "updated file",
  "attributes": {
    "details": "File details",
    "thumbnail": "Thumbnail grösse",
    "smallPic": "Small image size",
    "bigPic": "Big image size",
    "quality": "Image quality",
    "info": "Info",
    "name": "Name",
    "title": "Name",
    "desc": "Beschreibung",
    "alt": "Alt",
    "key": "Schlüssel",
    "type": "Filetype",
  },
});
