define({
    "attributes": {
      "title": "Title",
      "backupDatabase": "Backup Datenbank",
      "restoreDatabase": "Datenbank wiederherstellen",
      "domain": "Standard Url"
    },
	"development": "Entwicklung",
	"backend_development": "Backend im Entwicklungsmodus",
	"frontend_development": "Frontend im Entwicklungsmodus",
	"cancel": "Abbrechen",
	"deleteModel": "Löschen",
	"navigation": "Allgemein",
	"save": "Speichern",
    "date": "Datum",
    "publish": "Veröffentlichen",
    "unpublish": "Unveröffentlichen",
    "dateformat": "%d.%m.%y %H:%m:%S",
    "sunday": "Sonntag",
    "monday": "Montag",
    "tuesday": "Dienstag",
    "wednesday": "Mittwoch",
    "thursday": "Donnerstag",
    "friday": "Freitag",
    "saturday": "Samstag",
    "january": "Jänner",
    "february": "Februar",
    "march": "März",
    "april": "April",
    "may": "Mai",
    "june": "Juni",
    "july": "July",
    "august": "August",
    "september": "September",
    "october": "Oktober",
    "november": "November",
    "december": "Dezember"
});
